### ISSUE TITLE
Bug changement niveau vers "Beggar"

### ISSUE THREAD

**Issue by ecamtest** [IlBaroneJaja/MoneyRain#24]
Un bug survient lorsque le niveau sélectionné est autre que "Beggar" et que l'on veut retourner sur "Beggar". 
Comment reproduire le bug :
- Sélectionner un niveau autre que "Beggar" dans les settings
- Revenir au menu principal via le bouton < Menu
- Aller de nouveau dans les settings
- Choisir le niveau "Beggar"
  Constatation : le niveau ne change pas et reste comme précédemment. Cependant, on peut choisir un autre que niveau que "Beggar" sans problème. Et du coup "Beggar" redevient accessible ...

**Comment by IlBaroneJaja** [comment]
Résolu.
(Un seul composant reste: le Spinner. Plus de bouton intermédiaire générant la boîte de dialogue. On va directement interroger le Spinner pour obtenir la liste des items disponibles (Beggar,trader,...))
