### ISSUE TITLE
Ralentissement au changement de décor

### ISSUE THREAD

**Issue by IlBaroneJaja** [IlBaroneJaja/MoneyRain#29]
Plus un problème persistant qu'un bug à part entière: le changement de décor nécessite un chargement visiblement important, et ça lag plutôt pas mal :+1: 

Des idées de résolution?

**Comment by LioGoss** [comment]
Sur Bluestacks uniquement ou tu as testé sur un device android?

**Comment by IlBaroneJaja** [comment]
Oui sur l'emulateur de devices, ca lague aussi ! Il faudrait trouver un moyen de précharger en mémoire la ressource. Mais je crois que dans l'histoire, c'est l'affichage même qui prend du temps...

**Comment by ecamtest** [comment]
Un conteneur d'images se charge au lancement de l'application + fait des ajustements (nécessité de connaître dimensions écran) au lancement d'une partie. Conclusion : plus de lags lors d'ajouts d'éléments du décor mais lancement application / partie un peu plus long
